# Generated by Django 5.0.4 on 2024-05-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("pub_date", models.DateTimeField()),
                ("content", models.TextField()),
                (
                    "post_type",
                    models.CharField(
                        choices=[("news", "News"), ("article", "Article")], max_length=7
                    ),
                ),
                ("category", models.CharField(max_length=100)),
            ],
        ),
    ]
